name: Pull QMD Files

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  pull-qmd-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: hareshsuppiah/sourcerepo
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
          path: source

      - name: Find and Copy QMD Files
        run: |
          mkdir -p temp-repo
          find source -type f -name "*.qmd" -exec cp {} temp-repo/ \;

      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: hareshsuppiah/targetrepo
          token: ${{ secrets.GH_TOKEN }}
          path: target

      - name: Copy QMD Files to Target Repository
        run: |
          cp temp-repo/*.qmd target/
          cd target
          git config user.email "haresh@humanperformance.sg"
          git config user.name "hareshsuppiah"
          git add .
          git commit -m "Update QMD files from source repository"
          git push
